version: '3'

services:
    server:
        container_name: server
        depends_on: [cache]
        build: ./server
        expose:
            - ${API_PORT}
        environment:
            - CHOKIDAR_USEPOLLING=true
            - API_PORT=${API_PORT}
        ports: 
            - ${API_PORT}:${API_PORT}
        volumes:
            - ./server/src:/srv/app/music-quiz-server/src
        command: npm run dev

    client:
        container_name: react
        restart: always
        build: ./client
        expose:
            - ${REACT_APP_PORT}
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_PORT=${REACT_APP_PORT}
            - API_BASE_URL=${API_URL}:${API_PORT}
            - PORT=${REACT_APP_PORT}
        ports:
            - ${REACT_APP_PORT}:${REACT_APP_PORT}
        volumes:
            - ./client/src:/srv/app/music-quiz-client/src
            - ./client/src/public:/srv/app/music-quiz-client/src/public
        links:
            - server
        command: npm run start

    cache:
        container_name: redis
        image: redis:6.2-alpine
        restart: always
        ports:
        - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes: 
        - cache:/data
volumes:
  cache:
    driver: local
